apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: my-rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: rails-app
  labels:
    app: rails-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: rails-app

